### ISSUE TITLE
Label Description for Experiment Group

### ISSUE THREAD

**Issue by nirajgiriXD** [GoogleChromeLabs/privacy-sandbox-dev-support#269] opened 2024-03-01 10:14 UTC
### Discussed in https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/discussions/268

<div type='discussions-op-text'>

<sup>Originally posted by **nirajgiriXD** March  1, 2024</sup>
Chrome is set to introduce a new header `Sec-Cookie-Deprecation` containing `label` as the value which will allow websites to identify the specific `experiment group` a browser belongs to. I've been searching for information on these labels, resembling something like the table provided, but couldn't find anything. Is there a recommended site or resource where one can gain insight into these labels?

| **Label** | **% of browser** | Description |PS R&M APIs | 3PC |
| ---- | ---- | ---- | ---- | ---- |
| `control_1.1` | 0.25 |  | Disabled | Enabled |
| `control_1.2` | 0.25 |  | Disabled | Enabled |
| `control_1.3` | 0.25 |  | Disabled | Enabled |
| `control_1.4` | 0.25 |  | Disabled | Enabled |
| `control_2` | 0.25 |  | Disabled | Disabled |
| `label_only_1` | 1.5 |  |  |  |
| `label_only_2` | 1.5 |  |  |  |
| `label_only_3` | 1.5 |  | Enabled | Disabled |
| `label_only_4` | 1.5 |  |  |  |
| `label_only_5` | 1.5 |  |  |  |
| `treatment_1.1` | 0.25 |  |  |  |
| `treatment_1.2` | 0.25 |  |  |  |
| `treatment_1.3` | 0.25 |  |  |  |

`Note`: I couldn't find any descriptions of these labels in the [Chrome-facilitated testing](https://developers.google.com/privacy-sandbox/setup/web/chrome-facilitated-testing).
</div>

**Comment by samdutton** [comment] 2024-03-01 11:47
Duplicate of #268.

**Closed by samdutton** 2024-03-01 11:47 UTC
