### ISSUE TITLE
Behavior of 'ar_debug' cookie, 1P_JAR, NID, __Secure-3PSID, __Secure-3PAPISID, __Secure-3PSIDTS, __Secure-3PSIDCC after 3PCD

### ISSUE THREAD

**Issue by nainesh279** [GoogleChromeLabs/privacy-sandbox-dev-support#234] opened 2024-01-22 13:29 UTC
Hello,
What will be the behavior of following cookies after 3PCD:

1. ar_debug: Probably used for Google Analytics.
2. 1P_JAR
3. NID
4. __Secure-3PSID
5. __Secure-3PAPISID
6. __Secure-3PSIDTS
7.  __Secure-3PSIDCC
It seems like except 1st, all other are used by Google Recaptcha.
Do we need to handle any of these cookies? Will the 3PCD affect any of these?
Thank you

**Comment by samdutton** [comment] 2024-02-01 23:34
All third-party cookies will be affected by third-party cookie deprecation, subject to [temporary exceptions](https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/preserving-critical-user-experiences) and [user settings](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2024jan#identifying_third-party_cookie_restrictions). This includes third-party cookies set by Google products and services.

**Comment by samdutton** [comment] 2024-02-01 23:36
Closing: duplicate of #229.

**Closed by samdutton** 2024-02-01 23:36 UTC
Labels: third-party-cookie-deprecation
